{% set name = "surfe" %}
{% set version = '0.6.0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"

source:
  git_url: https://github.com/Loop3D/surfe
  git_tag: master

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - scikit-build-core
    - git
    - pybind11
    - pip
    - cmake
  host:
    - pip
    - python
    - numpy
    - python >=3.8
    - scikit-build-core
  run:
    - numpy
    - python >=3.8


about:
  home: "https://github.com/Loop3D/surfe"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Generalised radial basis function interpolation"
  dev_url: 

extra:
  recipe-maintainers:
    - lachlangrose
