{% set name = "surfe" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Loop3D/surfe
  git_tag: master

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    - cython
    - setuptools
    - scikit-build
    - numpy
  run:
    - numpy


about:
  home: "https://github.com/Loop3D/surfe"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Generalised radial basis function interpolation"
  dev_url: 

extra:
  recipe-maintainers:
    - lachlangrose
