{% set name = "surfe" %}
{% set version = 0.31 %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Loop3D/surfe
  git_tag: master

build:
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  build:
    - {{ compiler('c') }}
    - scikit-build
    - git
  host:
    - pip
    - python
    - cython
    - setuptools
    - scikit-build
    - numpy
  run:
    - numpy


about:
  home: "https://github.com/Loop3D/surfe"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Generalised radial basis function interpolation"
  dev_url: 

extra:
  recipe-maintainers:
    - lachlangrose
