name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: setup miniconda
      uses: goanpeca/action-setup-conda@v1
      with:
        python-version: ${{ matrix.python }}
    - name: print python
      run: |
        python --version 
#     - name: Build project
#       uses: nicledomaS/cmake_build_action@v1
#       with:
#         submodule_update: ON
#         run_tests: ON
#         unit_test_build: -Dtest=ON
#         cmake_args: -DEIGEN3_INCLUDE_DIR=eigen-git-mirror
#     - name: print
#       run: |
#         cd build
#         ls -l
#     - name: Development build pre-release
#       uses: "marvinpinto/action-automatic-releases@latest"
#       with: 
#         repo_token: "${{ secrets.GITHUB_TOKEN }}"
#         automatic_release_tag: "latest"
#         prerelease: true
#         title: "Development Build"
#         files: |
#           build/*.so
#         id: "automatic_releases"  
#   build-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout surfe
#         uses: actions/checkout@v2.0.0
#       - name: Build project
#         uses: nicledomaS/cmake_build_action@v1
#         with:
#           submodule_update: ON
#           run_tests: ON
#           unit_test_build: -Dtest=ON
#           cmake_args: -DEIGEN3_INCLUDE_DIR=eigen-git-mirror


