name: publish_conda

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Loop Conda
        uses: Loop3D/conda-publish-action@1.6
        with:
          subdir: "conda"
          anacondatoken: ${{ secrets.CONDA }}
          platforms: "linux"
  windows:
    runs-on: windows-2016
    strategy:
      matrix:
        python: ['3.6','3.7','3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }} 
        activate-environment: loop    
    - name: Installing dependencies
      shell: bash -l {0}
      run: |
        python --version
        conda install -c conda-forge conda-build
        cd conda
        conda build -c anaconda -c conda-forge -c loop3d -c conda-forge/label/cf202003  -c pytorch -c fcakyon -c districtdatalabs --output-folder . .
    - name: upload to anaconda
      shell: bash -l {0}
      
      run: |
        export ANACONDA_API_TOKEN=${{ secrets.CONDA }}
        anaconda upload --label main win-64/*.tar.bz2
  
