name: Python package build and publish

on: [push]
  
jobs:
  manylinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine 
    - name: Build manylinux Python wheels
      uses: Loop3d/python-wheels-manylinux-build@v0.2.2-manylinux2014_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        build-requirements: 'cmake scikit-build'
        system-packages: ''
        package-path: ''
        pip-wheel-args: ''
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload wheelhouse/*-manylinux*.whl 
      
#   osx:
#     runs-on: macos-latest
#     strategy:
#       matrix:
#         python: [3.6, 3.7,3.8]
#     steps:
#     - uses: actions/checkout@v2
#     - name: submodules
#       run: |
#         git submodule update --init --recursive
#     - name: Set up Python
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ matrix.python }} 
#     - name: install omp
#       run: |
#         brew install libomp  
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install twine scikit-build cmake
#         pip wheel .
        
  build-windows:
    runs-on: windows-2016
    strategy:
      matrix:
        python: ['3.6','3.7','3.8']
    steps:
    - uses: actions/checkout@v2
    - name: submodules
      shell: bash -l {0}
      run: |
        git submodule update --init --recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }} 
        activate-environment: loop    
    - name: Installing dependencies
      shell: bash -l {0}
      run: |
        python --version
        pip install cmake scikit-build
    - name: Building surfe wheel
      shell: bash -l {0}
      run: |
        python setup.py bdist_wheel
        python setup.py bdist
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      shell: bash -l {0}
      run : |
        pip install twine
        twine upload dist/*.whl

