name: Python package build and publish

on:
  push
#   release:
#     types: [created, edited]

jobs:
  build_wheels_macos:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]#, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_BUILD: " cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686" #no 32bit
          CIBW_BEFORE_BUILD: "pip install oldest-supporter-numpy cython scikit-build-core pybind11" 
#           CIBW_TEST_REQUIRES: pytest
#           CIBW_TEST_COMMAND: pytest test
      # - name: Publish wheels to PyPI
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run : |
      #     pip install twine
      #     python -m twine upload ./wheelhouse/*.whl       
